/**
 * Stable error codes. Like taxonomy codes these appear in API responses and logs,
 * so they are additive-only.
 */

export const ERROR_CODES = Object.freeze({
  // validation
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INVALID_SPAN: 'INVALID_SPAN',
  INVALID_QUERY: 'INVALID_QUERY',
  UNSUPPORTED_FORMAT: 'UNSUPPORTED_FORMAT',

  // configuration
  CONFIG_INVALID: 'CONFIG_INVALID',
  CONFIG_MISSING: 'CONFIG_MISSING',
  TAXONOMY_UNKNOWN_CODE: 'TAXONOMY_UNKNOWN_CODE',
  DETECTOR_DUPLICATE_ID: 'DETECTOR_DUPLICATE_ID',
  MIGRATION_FAILED: 'MIGRATION_FAILED',

  // storage
  STORAGE_UNAVAILABLE: 'STORAGE_UNAVAILABLE',
  STORAGE_QUERY_FAILED: 'STORAGE_QUERY_FAILED',
  STORAGE_WRITE_FAILED: 'STORAGE_WRITE_FAILED',

  // transport
  TRANSPORT_FAILED: 'TRANSPORT_FAILED',
  TRANSPORT_TIMEOUT: 'TRANSPORT_TIMEOUT',
  TRANSPORT_CIRCUIT_OPEN: 'TRANSPORT_CIRCUIT_OPEN',

  // detector
  DETECTOR_FAILED: 'DETECTOR_FAILED',
  DETECTOR_TIMEOUT: 'DETECTOR_TIMEOUT',
  DETECTOR_CONTRACT_VIOLATION: 'DETECTOR_CONTRACT_VIOLATION',
  JUDGE_UNAVAILABLE: 'JUDGE_UNAVAILABLE',
  JUDGE_BUDGET_EXCEEDED: 'JUDGE_BUDGET_EXCEEDED',

  // auth
  AUTH_MISSING: 'AUTH_MISSING',
  AUTH_INVALID: 'AUTH_INVALID',
  /** Writes are disabled on this deployment; no credential can satisfy it. */
  INGEST_DISABLED: 'INGEST_DISABLED',

  // not found
  NOT_FOUND: 'NOT_FOUND',

  // rate limit
  RATE_LIMITED: 'RATE_LIMITED',

  // internal
  INTERNAL: 'INTERNAL',
  SDK_INTERNAL: 'SDK_INTERNAL',
  QUEUE_OVERFLOW: 'QUEUE_OVERFLOW',
});

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
